# Index

# Quiz 01 : 문자열 압축

> 출처
>> 프로그래머스

> 문제 설명
>> 데이터 처리 전문가가 되고 싶은 "어피치"는 문자열을 압축하는 방법에 대해 공부를 하고 있습니다. 최근에 대량의 데이터 처리를 위한 간단한 비손실 압축 방법에 대해 공부를 하고 있는데, 문자열에서 같은 값이 연속해서 나타나는 것을 그 문자의 개수와 반복되는 값으로 표현하여 더 짧은 문자열로 줄여서 표현하는 알고리즘을 공부하고 있습니다.
>>
>> 간단한 예로 "aabbaccc"의 경우 "2a2ba3c"(문자가 반복되지 않아 한번만 나타난 경우 1은 생략함)와 같이 표현할 수 있는데, 이러한 방식은 반복되는 문자가 적은 경우 압축률이 낮다는 단점이 있습니다. 예를 들면, "abcabcdede"와 같은 문자열은 전혀 압축되지 않습니다. "어피치"는 이러한 단점을 해결하기 위해 문자열을 1개 이상의 단위로 잘라서 압축하여 더 짧은 문자열로 표현할 수 있는지 방법을 찾아보려고 합니다.  
>>
>> 예를 들어, "ababcdcdababcdcd"의 경우 문자를 1개 단위로 자르면 전혀 압축되지 않지만, 2개 단위로 잘라서 압축한다면   
>> "2ab2cd2ab2cd"로 표현할 수 있습니다. 다른 방법으로 8개 단위로 잘라서 압축한다면 "2ababcdcd"로 표현할 수 있으며, 이때가 가장 짧게 압축하여 표현할 수 있는 방법입니다.  
>>
>> 다른 예로, "abcabcdede"와 같은 경우, 문자를 2개 단위로 잘라서 압축하면  
>> "abcabc2de"가 되지만, 3개 단위로 자른다면 "2abcdede"가 되어 3개 단위가 가장 짧은 압축 방법이 됩니다. 이때 3개 단위로 자르고 마지막에 남는 문자열은 그대로 붙여주면 됩니다.  
>>
>> 압축할 문자열 s가 매개변수로 주어질 때, 위에 설명한 방법으로 1개 이상 단위로 문자열을 잘라 압축하여 표현한 문자열 중 가장 짧은 것의 길이를 return 하도록 solution 함수를 완성해주세요.

> 제한 사항  
>> - s의 길이는 1 이상 1,000 이하입니다.  
>> - s는 알파벳 소문자로만 이루어져 있습니다.  

> 입출력의 예  
>> | s | result |  
>> | - | - |  
>> | "aabbaccc" | 7 |  
>> | "ababcdcdababcdcd" | 9 |  
>> | "abcabcdede" | 8 |  
>> | "abcabcabcabcdededededede" | 14 |  
>> | "xababcdcdababcdcd" | 17 |
<br/>

> 입출력의 예에 대한 설명  
>> 입출력 예 #1  
>> 문자열을 1개 단위로 잘라 압축했을 때 가장 짧습니다.  
>
>> 입출력 예 #2  
>> 문자열을 8개 단위로 잘라 압축했을 때 가장 짧습니다.  
>
>> 입출력 예 #3  
>> 문자열을 3개 단위로 잘라 압축했을 때 가장 짧습니다.  
>
>> 입출력 예 #4  
>> 문자열을 2개 단위로 자르면 "abcabcabcabc6de" 가 됩니다.  
>> 문자열을 3개 단위로 자르면 "4abcdededededede" 가 됩니다.  
>> 문자열을 4개 단위로 자르면 "abcabcabcabc3dede" 가 됩니다.  
>> 문자열을 6개 단위로 자를 경우 "2abcabc2dedede"가 되며, 이때의 길이가 14로 가장 짧습니다.  
>
>> 입출력 예 #5  
>> 문자열은 제일 앞부터 정해진 길이만큼 잘라야 합니다.  
>> 따라서 주어진 문자열을 x / ababcdcd / ababcdcd 로 자르는 것은 불가능 합니다.  
>> 이 경우 어떻게 문자열을 잘라도 압축되지 않으므로 가장 짧은 길이는 17이 됩니다.  


In [53]:
s1 = "aabbaccc"                 # 8 -> 7
s2 = "ababcdcdababcdcd"         # 16 - > 9
s3 = "abcabcdede"               # 10 -> 8
s4 = "abcabcabcabcdededededede" # 24 -> 14
s5 = "xababcdcdababcdcd"        # 17 -> 17
s = s1, s2, s3, s4, s5

('aabbaccc',
 'ababcdcdababcdcd',
 'abcabcdede',
 'abcabcabcabcdededededede',
 'xababcdcdababcdcd')

## -01 : 내 풀이

In [56]:
def quiz_01(s) :
    answer = []
    for i in range(1, (len(s)//2)+1) : # 묵음 단위(1개 ~ 전체/2)    # 1/2 길이 이상은 어차피 페어가 될 수 없으므로 하나로 봐야한다
        cnt = 0
        ans = ''
        anss = ''
        for j in range(0, len(s), i) :   # 0~(len)까지 묶음단위(stp)로 비교 # ex. (0, 20, 3) -> [0:3] [3:6] / [3:6] [6:9] / [9:12] ...
            if s[j:j+i] != s[j+i:j+i+i] :
                if cnt > 0 :
                    ans = str(cnt+1) + s[j:j+i]   # ans 에 cnt 와 묶음 정보를 갱신한다
                    anss += ans                 # anss 에 종합 정보를 갱신한다 
                    cnt = 0
                else :
                    ans = s[j:j+i]
                    anss += ans
            else :
                cnt += 1

        answer.append(anss)                     # step에 따른 결과를 리스트로 갱신한다

    min_s = len(s)

    # 길이를 비교한다
    for new_s in answer :
        if len(new_s) < min_s and len(new_s) != 0 :
            min_s = len(new_s)
        
    return min_s, print(answer)

for i in s :
    print(quiz_01(i),'\n')

['2a2ba3c', 'aabbaccc', 'aabbaccc', 'aabbaccc']
(7, None) 

['ababcdcdababcdcd', '2ab2cd2ab2cd', 'ababcdcdababcdcd', 'ababcdcdababcdcd', 'ababcdcdababcdcd', 'ababcdcdababcdcd', 'ababcdcdababcdcd', '2ababcdcd']
(9, None) 

['abcabcdede', 'abcabc2de', '2abcdede', 'abcabcdede', 'abcabcdede']
(8, None) 

['abcabcabcabcdededededede', 'abcabcabcabc6de', '4abcdededededede', 'abcabcabcabc3dede', 'abcabcabcabcdededededede', '2abcabc2dedede', 'abcabcabcabcdededededede', 'abcabcabcabcdededededede', 'abcabcabcabcdededededede', 'abcabcabcabcdededededede', 'abcabcabcabcdededededede', 'abcabcabcabcdededededede']
(14, None) 

['xababcdcdababcdcd', 'xababcdcdababcdcd', 'xababcdcdababcdcd', 'xababcdcdababcdcd', 'xababcdcdababcdcd', 'xababcdcdababcdcd', 'xababcdcdababcdcd', 'xababcdcdababcdcd']
(17, None) 



## -02 : 다른 사람 풀이

In [59]:
def compress(text, tok_len):
    words = [text[i:i+tok_len] for i in range(0, len(text), tok_len)]
    res = []
    cur_word = words[0]
    cur_cnt = 1
    for a, b in zip(words, words[1:] + ['']):
        if a == b:
            cur_cnt += 1
        else:
            res.append([cur_word, cur_cnt])
            cur_word = b
            cur_cnt = 1
    return sum(len(word) + (len(str(cnt)) if cnt > 1 else 0) for word, cnt in res)

def quiz_01_2(text):
    return min(compress(text, tok_len) for tok_len in list(range(1, int(len(text)/2) + 1)) + [len(text)])

for x in s:
    print(quiz_01_2(x))

7
9
8
14
17


# Quiz 02 : 행렬 테두리 회전하기

> 문제 설명
>> rows x columns 크기인 행렬이 있습니다. 행렬에는 1부터 rows x columns까지의 숫자가 한 줄씩 순서대로 적혀있습니다.
>> 이 행렬에서 직사각형 모양의 범위를 여러 번 선택해, 테두리 부분에 있는 숫자들을 시계방향으로 회전시키려 합니다.
>> 각 회전은 (x1, y1, x2, y2)인 정수 4개로 표현하며, 그 의미는 다음과 같습니다
>>   - x1 행 y1 열부터 x2 행 y2 열까지의 영역에 해당하는 직사각형에서 테두리에 있는 숫자들을 한 칸씩 시계방향으로 회전합니다.
>>
>> 다음은 6 x 6 크기 행렬의 예시입니다.
>>> <img src='https://grepp-programmers.s3.ap-northeast-2.amazonaws.com/files/ybm/4c3c0fab-11f4-43b6-b290-6f4017e9379f/grid_example.png' width=400>
>> <br/>
>> 이 행렬에 (2, 2, 5, 4) 회전을 적용하면, 아래 그림과 같이 2행 2열부터 5행 4열까지 영역의 테두리가 시계방향으로 회전합니다. 이때, 중앙의 15와 21이 있는 영역은 회전하지 않는 것을 주의하세요.
>>> <img src='https://grepp-programmers.s3.ap-northeast-2.amazonaws.com/files/ybm/962df137-5c71-4091-ad9f-8e322910c1ab/rotation_example.png' width=400>
>> <br/>
>> 행렬의 세로 길이(행 개수) rows, 가로 길이(열 개수) columns, 그리고 회전들의 목록 queries가 주어질 때, 각 회전들을 배열에 적용한 뒤, 그 회전에 의해 위치가 바뀐 숫자들 중 가장 작은 숫자들을 순서대로 배열에 담아 return 하도록 solution 함수를 완성해주세요.

> 제한 사항
>> - rows는 2 이상 100 이하인 자연수입니다.
>> - columns는 2 이상 100 이하인 자연수입니다.
>> - 처음에 행렬에는 가로 방향으로 숫자가 1부터 하나씩 증가하면서 적혀있습니다.
>>   - 즉, 아무 회전도 하지 않았을 때, i 행 j 열에 있는 숫자는 ((i-1) x columns + j)입니다.
>> - queries의 행의 개수(회전의 개수)는 1 이상 10,000 이하입니다.
>> - queries의 각 행은 4개의 정수 [x1, y1, x2, y2]입니다.
>>   - x1 행 y1 열부터 x2 행 y2 열까지 영역의 테두리를 시계방향으로 회전한다는 뜻입니다.
>>   - 1 ≤ x1 < x2 ≤ rows, 1 ≤ y1 < y2 ≤ columns입니다.
>>   - 모든 회전은 순서대로 이루어집니다.
>>   - 예를 들어, 두 번째 회전에 대한 답은 첫 번째 회전을 실행한 다음, 그 상태에서 두 번째 회전을 실행했을 때 이동한 숫자 중 최솟값을 구하면 됩니다.

> 입출력 예시
>> | rows | columns | queies | result |
>> | - | - | - | - |
>> | 6 | 6 | [[2,2,5,4],[3,3,6,6],[5,1,6,3]] | [8, 10, 25] |
>> | 3 | 3 | [[1,1,2,2],[1,2,2,3],[2,1,3,2],[2,2,3,3]] | [1, 1, 5, 3] |
>> | 100 | 97 | [[1,1,100,97]] | [1]]

> 입출력 예 설명
>> 입출력 예 #1
>>> - 회전을 수행하는 과정을 그림으로 표현하면 다음과 같습니다.  
>>> <img src='https://grepp-programmers.s3.ap-northeast-2.amazonaws.com/files/ybm/8c8cdd84-d0ec-4b9d-bdf7-f100d0098c5e/example1.png' width=600> <img src='https://grepp-programmers.s3.ap-northeast-2.amazonaws.com/files/ybm/962df137-5c71-4091-ad9f-8e322910c1ab/rotation_example.png' width=400>
>> <br/>
>
>> 입출력 예 #2
>>> - 회전을 수행하는 과정을 그림으로 표현하면 다음과 같습니다.  
>>> <img src='https://grepp-programmers.s3.ap-northeast-2.amazonaws.com/files/ybm/e3fce2bf-9da9-41e4-926a-5d19b4f31188/example2.png' width=500>
>
>> 입출력 예 #3
>>> - 이 예시에서는 행렬의 테두리에 위치한 모든 칸들이 움직입니다. 따라서, 행렬의 테두리에 있는 수 중 가장 작은 숫자인 1이 바로 답이 됩니다.

In [2]:
r1, c1, q1 = 6, 6, [[2,2,5,4],[3,3,6,6],[5,1,6,3]]            # [8, 10, 25]
r2, c2, q2 = 3, 3, [[1,1,2,2],[1,2,2,3],[2,1,3,2],[2,2,3,3]]  # [1, 1, 5, 3]
r3, c3, q3 = 100, 97, [[1,1,100,97]]                             # [1]

r = r1,r2,r3
c = c1,c2,c3
q = q1,q2,q3

for input in zip(r,c,q) :
    print(input)

(6, 6, [[2, 2, 5, 4], [3, 3, 6, 6], [5, 1, 6, 3]])
(3, 3, [[1, 1, 2, 2], [1, 2, 2, 3], [2, 1, 3, 2], [2, 2, 3, 3]])
(100, 97, [[1, 1, 100, 97]])


In [51]:
import numpy as np
import pandas as pd

a = np.array(list(range(1,r1 * c1 +1))).reshape(r1,c1)
d = pd.DataFrame(a,columns=range(1,c1+1), index=range(1,r1+1))
# print(a)
display(d)
# print(q1)
print(q1[1])
# print(q1[0][0])
# print(q1[0][1])
# print(q1[0][2])
# print(q1[0][3])
display(d.loc[q1[0][0]:q1[0][2],q1[0][1]:q1[0][3]])


1   2   3   4   5   6
1   1   2   3   4   5   6
2   7   8   9  10  11  12
3  13  14  15  16  17  18
4  19  20  21  22  23  24
5  25  26  27  28  29  30
6  31  32  33  34  35  36

[3, 3, 6, 6]


2   3   4
2   8   9  10
3  14  15  16
4  20  21  22
5  26  27  28

In [55]:
r1, c1, q1 = 6, 6, [[2,2,5,4],[3,3,6,6],[5,1,6,3]]            # [8, 10, 25]
r2, c2, q2 = 3, 3, [[1,1,2,2],[1,2,2,3],[2,1,3,2],[2,2,3,3]]  # [1, 1, 5, 3]
r3, c3, q3 = 100, 97, [[1,1,100,97]]                          # [1]

rs = r1,r2,r3
cs = c1,c2,c3
qs = q1,q2,q3

## -01 : 나의 최초 풀이 (오답)

In [56]:
# 회전을 진행 한 것을 유지해서 회전을 반복한다는 것을 이해하지 못하고 한 풀이

import numpy as np
import pandas as pd

def quiz_02_1(row, col, q) :
    ar = np.arange(1,row * col +1).reshape(row,col)
    df = pd.DataFrame(ar, columns=range(1,col+1), index=range(1,row+1))
    answer = []
    for i in q :
        area1 = (df.loc[i[0]:i[2]+1,i[1]]).min()
        area2 = (df.loc[i[0]:i[2]+1,i[3]]).min()
        area3 = (df.loc[i[0],       i[1]+1:i[3]]).min()
        area4 = (df.loc[i[2],       i[1]+1:i[3]]).min()
        minimum = min(area1,area2,area3,area4)
        answer.append(minimum)
    return answer

for input in zip(rs,cs,qs) :
    row, col, q = input
    print(quiz_02_1(row, col, q))

[8, 15, 25]
[1, 2, 4, 5]
[1]


## -02 : 나의 풀이 (정답)

In [67]:
import numpy as np

def solution(row, col, q) :

    def move_min(org_ar, new_ar,r1,c1,r2,c2) :
        org_ar = new_ar * 1
        m1 = new_ar[r1-1,c1:c2] = org_ar[r1-1,c1-1:c2-1]     # row 1 행 우측 이동
        m2 = new_ar[r1:r2,c2-1] = org_ar[r1-1:r2-1,c2-1]     # col 2 열 아래 이동
        m3 = new_ar[r2-1,c1-1:c2-1] = org_ar[r2-1,c1:c2]     # ro2 2 행 좌측 이동
        m4 = new_ar[r1-1:r2-1,c1-1] = org_ar[r1:r2,c1-1]     # col 1 열 위로 이동
        minimum = int(min(min(m1),min(m2),min(m3),min(m4)))
        return new_ar, minimum

    org_ar = np.arange(1,row * col +1).reshape(row,col)
    new_ar = org_ar * 1
    answer = []
    cnt = 0
    print('org : {}\n'.format(cnt), org_ar)

    for i in q :
        cnt += 1
        row1,col1,row2,col2 = i
        new_ar, minimum = move_min(org_ar,new_ar,row1,col1,row2,col2)
        answer.append(minimum)
        print('new : {}\n'.format(cnt), new_ar)
    return answer


for input in zip(rs,cs,qs) :
    row, col, q = input
    print(solution(row, col, q))

org : 0
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
new : 1
 [[ 1  2  3  4  5  6]
 [ 7 14  8  9 11 12]
 [13 20 15 10 17 18]
 [19 26 21 16 23 24]
 [25 27 28 22 29 30]
 [31 32 33 34 35 36]]
new : 2
 [[ 1  2  3  4  5  6]
 [ 7 14  8  9 11 12]
 [13 20 21 15 10 17]
 [19 26 28 16 23 18]
 [25 27 33 22 29 24]
 [31 32 34 35 36 30]]
new : 3
 [[ 1  2  3  4  5  6]
 [ 7 14  8  9 11 12]
 [13 20 21 15 10 17]
 [19 26 28 16 23 18]
 [31 25 27 22 29 24]
 [32 34 33 35 36 30]]
[8, 10, 25]
org : 0
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
new : 1
 [[4 1 3]
 [5 2 6]
 [7 8 9]]
new : 2
 [[4 2 1]
 [5 6 3]
 [7 8 9]]
new : 3
 [[4 2 1]
 [7 5 3]
 [8 6 9]]
new : 4
 [[4 2 1]
 [7 6 5]
 [8 9 3]]
[1, 1, 5, 3]
org : 0
 [[   1    2    3 ...   95   96   97]
 [  98   99  100 ...  192  193  194]
 [ 195  196  197 ...  289  290  291]
 ...
 [9410 9411 9412 ... 9504 9505 9506]
 [9507 9508 9509 ... 9601 9602 9603]
 [9604 9605 9606 ... 9698 9699 9700]]
new : 1
 