In [4]:
import numpy as np

ar = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(ar.shape, ar.ndim)

(3, 3) 2


In [5]:
import torch

t1 = torch.FloatTensor([1,2,3])
t2 = torch.FloatTensor([[4],[5],[6]])

print(t1 + t2)

tensor([[5., 6., 7.],
        [6., 7., 8.],
        [7., 8., 9.]])


In [1]:
import torch

t = torch.FloatTensor([[[1],[2],[3]], [[4],[5],[6]], [[7],[8],[9]]])
print(t.squeeze(), t.squeeze().shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.Size([3, 3])


In [2]:
t = torch.FloatTensor([[1,2,3,4,], [5,6,7,8]])
t = t.view([-1,2])

print(t)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [3]:
t1 = torch.FloatTensor([[1,2,3,4]])
t2 = torch.FloatTensor([[5,6,7,8]])

print(torch.cat([t1, t2], axis=0))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])


In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

w = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

hypothesis = # TODO

In [14]:
x_train = torch.FloatTensor([73, 88, 75, 77], [93, 88, 93, 95], [89, 91, 90, 89], [96, 98, 100, 97], [73, 66, 70, 68])

w = torch.zeros((1), requires_grad=True)
print(w.shape)

TypeError: new() received an invalid combination of arguments - got (list, list, list, list, list), but expected one of:
 * (*, torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)
